### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by tomp1k** [i0null/homebridge-lgtv-2012#5]
I am getting these error after installation.
Thank you for advice.

[TV] TV [10.0.1.6]: On
/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:93
        tv.get_volume( (volume) => {
          ^

TypeError: Cannot read property 'get_volume' of null
    at /usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:93:11
    at /usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:58:13
    at lgtv.http.get.http.request.send_command.get_volume.set_volume.cb.pair_request.new_session.cb [as new_session] (/usr/local/lib/node_modules/homebridge-lgtv-2012/node_modules/lgtv-2012/index.js:194:20)
    at lgtv_2012_accessory.connect.cb [as connect] (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:56:17)
    at lgtv_2012_accessory.connect.lgtv_2012_accessory.getState.lgtv_2012_accessory.setState.cb.getState.lgtv_2012_accessory.getVolume.cb.connect [as getVolume] (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:92:10)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:750:20)
    at Array.forEach (native)

**Comment by i0null** [comment]
Hi Sorry to bump an old thread, but are you still experiencing this issue, what node/homebridge versions are you running?

**Comment by martindex23** [comment]
Same problem here. 
I'm using the node  homebridge-config-ui-x v4.6.0 - node.js v10.16.0 
is it the correct info?

while restarting I've got this info:
Aug 16 17:24:59 raspberrypi homebridge[14695]: [8/16/2019, 5:24:59 PM] TypeError: Cannot read property 'get_volume' of null
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at connect (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:93:12)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at tv.new_session (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:58:13)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at lgtv.new_session (/usr/local/lib/node_modules/homebridge-lgtv-2012/node_modules/lgtv-2012/index.js:194:20)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at lgtv_2012_accessory.connect (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:56:17)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at lgtv_2012_accessory.getVolume (/usr/local/lib/node_modules/homebridge-lgtv-2012/index.js:92:10)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at Characteristic.Brightness.emit (events.js:198:13)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at Characteristic.Brightness.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at Array.forEach (<anonymous>)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at HAPServer.emit (events.js:198:13)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at IncomingMessage.emit (events.js:198:13)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at endReadableNT (_stream_readable.js:1129:12)
Aug 16 17:24:59 raspberrypi homebridge[14695]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Aug 16 17:24:59 raspberrypi homebridge[14695]: [8/16/2019, 5:24:59 PM] Got SIGTERM, shutting down Homebridge...
